# KRX 전체 종목 수집
* KRX(한국 거래소)의 상장 종목을 모두 가져오는 것을 목표로 한다.
* pandas와 FinanceDataReader를 활용한다.

## pandas(pd)&FinanceDataReader(fdr)

In [1]:
import pandas as pd

In [2]:
import FinanceDataReader as fdr
# 버전 확인
fdr.__version__

'0.9.31'

In [3]:
fdr.StockListing?

In [4]:
fdr.StockListing??

## fdr.StockListing

* ? : 어떤 리스트를 가져올 수 있을지 문서 확인 가능
* ?? : 코드

### 전체 리스트 보기

```python
Signature: fdr.StockListing(market)
Docstring:
read stock list of stock exchanges
* market: 'S&P500', 'NASDAQ', 'NYSE', 'AMEX', 'SSE', 'SZSE', 'HKEX', 'TSE', 'HOSE', 
        'KRX', 'KOSPI', 'KOSDAQ', 'KONEX'
        'KRX-DELISTING', 'KRX-MARCAP', 'KRX-ADMINISTRATIVE'
        'ETF/KR'
File:      c:\users\drimsys\anaconda3\lib\site-packages\financedatareader\data.py
Type:      function
```

### StockListing 속성 정리

* KRX : KRX 종목 전체
* SP500 : S&P500 종목
* NASDAQ : 나스닥 종목
* NYSE : 뉴욕증권거래소 종목
* KOSPI : KOSPI 종목
* KOSDAQ : KOSDAQ 종목
* KONEX : KONEX 종목
* KRX-DELISTING : 상장 폐지 종목
* KRX-MARCAP
* KRX-ADMINISTRATIVE
* ETF/KR
* AMEX
* SSE
* SZSE
* HKEX
* TSE
* HOSE

In [5]:
# KISPI 종목 가져오기
fdr.StockListing("KOSPI")

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,박대현,http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
6,152100,KOSPI,ARIRANG 200,NaN,NaN,NaT,NaN,NaN,NaN,NaN
7,295820,KOSPI,ARIRANG 200동일가중,NaN,NaN,NaT,NaN,NaN,NaN,NaN
8,253150,KOSPI,ARIRANG 200선물레버리지,NaN,NaN,NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
6963,069260,KOSPI,휴켐스,기타 화학제품 제조업,"화합물,화학제품 제조",2002-10-07,12월,신진용,http://www.huchems.com,서울특별시
6967,000540,KOSPI,흥국화재,보험업,손해보험,1974-12-05,12월,권중원,http://www.insurance.co.kr,서울특별시
6968,000547,KOSPI,흥국화재2우B,NaN,NaN,NaT,NaN,NaN,NaN,NaN
6969,000545,KOSPI,흥국화재우,NaN,NaN,NaT,NaN,NaN,NaN,NaN
6970,003280,KOSPI,흥아해운,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시

In [6]:
#KRX 종목 가져오기
df_krx = fdr.StockListing("KRX")
df_krx

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,전자부품 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,박대현,http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도
...,...,...,...,...,...,...,...,...,...,...
6968,000547,KOSPI,흥국화재2우B,NaN,NaN,NaT,NaN,NaN,NaN,NaN
6969,000545,KOSPI,흥국화재우,NaN,NaN,NaT,NaN,NaN,NaN,NaN
6970,003280,KOSPI,흥아해운,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시
6971,037440,KOSDAQ,희림,"건축기술, 엔지니어링 및 관련 기술 서비스업",설계 및 감리용역,2000-02-03,12월,"정영균, 이목운, 허철호 (각자대표)",http://www.heerim.com,서울특별시
6972,238490,KOSDAQ,힘스,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

## KRX 데이터 확인

* shape : 행, 열 개수 보기
* info() : 데이터 #,Column,on-Null Count,Dtype와 데이터 사용량 확인 가능
* describe() : 기술 통계 값 요약
* head() : 미리보기

In [8]:
# 행과 열 개수 보기
df_krx.shape

(6973, 10)

In [9]:
# 데이터 정보
# object : 문자(Symbol : 맨 앞에 0을 쓰고 싶으면 문자로!)
df_krx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6973 entries, 0 to 6972
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Symbol          6973 non-null   object
 1   Market          6973 non-null   object
 2   Name            6973 non-null   object
 3   Sector          2469 non-null   object
 4   Industry        2450 non-null   object
 5   ListingDate     2469 non-null   datetime64[ns]
 6   SettleMonth     2469 non-null   object
 7   Representative  2469 non-null   object
 8   HomePage        2321 non-null   object
 9   Region          2469 non-null   object
dtypes: datetime64[ns](1), object(9)
memory usage: 599.2+ KB

In [10]:
# 기술 통계 요약
df_krx.describe()

<ipython-input-10-296f0c9e3008>:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df_krx.describe()

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
count,6973,6973,6973,2469,2450,2469,2469,2469,2321,2469
unique,6973,3,6973,160,2300,1825,9,2342,2299,22
top,023460,KOSPI,신한G085SK하이닉콜,소프트웨어 개발 및 공급업,기업인수합병,1996-07-03 00:00:00,12월,-,http://www.maeil.com,서울특별시
freq,1,5301,1,145,27,8,2408,5,2,999
first,NaN,NaN,NaN,NaN,NaN,1956-03-03 00:00:00,NaN,NaN,NaN,NaN
last,NaN,NaN,NaN,NaN,NaN,2021-10-22 00:00:00,NaN,NaN,NaN,NaN

### Describe() 해석
* freq : 최빈값(top에 표시) -> freq가 1이면 유일한 값!
* count : 빈도수
* unique : 유일한 값 개수(count와 같으면 모두 유일한 값(freq=1)
* first, last : 날짜 데이터의 처음과 끝

In [7]:
# 미리보기(상위 5개만 보기)
df_krx.head()

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,전자부품 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,박대현,http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도

In [ ]:
# csv 파일로 저장